presubmits:
  openshift/windows-machine-config-operator:
  - agent: kubernetes
    always_run: true
    branches:
    - master
    context: ci/prow/build
    decorate: true
    decoration_config:
      skip_cloning: true
    labels:
      ci-operator.openshift.io/prowgen-controlled: "true"
      pj-rehearse.openshift.io/can-be-rehearsed: "true"
    name: pull-ci-openshift-windows-machine-config-operator-master-build
    rerun_command: /test build
    spec:
      containers:
      - args:
        - --artifact-dir=$(ARTIFACTS)
        - --give-pr-author-access-to-namespace=true
        - --sentry-dsn-path=/etc/sentry-dsn/ci-operator
        - --target=build
        command:
        - ci-operator
        env:
        - name: CONFIG_SPEC
          valueFrom:
            configMapKeyRef:
              key: openshift-windows-machine-config-operator-master.yaml
              name: ci-operator-master-configs
        image: ci-operator:latest
        imagePullPolicy: Always
        name: ""
        resources:
          requests:
            cpu: 10m
        volumeMounts:
        - mountPath: /etc/sentry-dsn
          name: sentry-dsn
          readOnly: true
      serviceAccountName: ci-operator
      volumes:
      - name: sentry-dsn
        secret:
          secretName: sentry-dsn
    trigger: (?m)^/test( | .* )build,?($|\s.*)
  - agent: kubernetes
    always_run: false
    branches:
    - master
    context: ci/prow/e2e-aws-ovn-kubernetes
    decorate: true
    decoration_config:
      skip_cloning: true
    labels:
      pj-rehearse.openshift.io/can-be-rehearsed: "true"
    name: pull-ci-openshift-windows-machine-config-operator-master-e2e-aws-ovn-kubernetes
    rerun_command: /test e2e-aws-ovn-kubernetes
    spec:
      containers:
      - args:
        - --artifact-dir=$(ARTIFACTS)
        - --give-pr-author-access-to-namespace=true
        - --secret-dir=/usr/local/e2e-aws-ovn-kubernetes-cluster-profile
        - --sentry-dsn-path=/etc/sentry-dsn/ci-operator
        - --target=e2e-aws-ovn-kubernetes
        - --template=/usr/local/e2e-aws-ovn-kubernetes
        command:
        - ci-operator
        env:
        - name: CLUSTER_NETWORK_TYPE
          value: OVNKubernetes
        - name: CLUSTER_TYPE
          value: aws
        - name: CONFIG_SPEC
          valueFrom:
            configMapKeyRef:
              key: openshift-windows-machine-config-operator-master.yaml
              name: ci-operator-master-configs
        - name: JOB_NAME_SAFE
          value: e2e-aws-ovn-kubernetes
        - name: TEST_COMMAND
          value: TEST_SUITE=openshift/conformance/parallel run-tests
        image: ci-operator:latest
        imagePullPolicy: Always
        name: ""
        resources:
          requests:
            cpu: 10m
        volumeMounts:
        - mountPath: /usr/local/e2e-aws-ovn-kubernetes-cluster-profile
          name: cluster-profile
        - mountPath: /usr/local/e2e-aws-ovn-kubernetes
          name: job-definition
          subPath: cluster-launch-installer-e2e.yaml
        - mountPath: /etc/sentry-dsn
          name: sentry-dsn
          readOnly: true
      serviceAccountName: ci-operator
      volumes:
      - name: cluster-profile
        projected:
          sources:
          - secret:
              name: cluster-secrets-aws
      - configMap:
          name: prow-job-cluster-launch-installer-e2e
        name: job-definition
      - name: sentry-dsn
        secret:
          secretName: sentry-dsn
    trigger: (?m)^/test( | .* )e2e-aws-ovn-kubernetes,?($|\s.*)
  - agent: kubernetes
    always_run: true
    branches:
    - master
    context: ci/prow/tools-test-e2e
    decorate: true
    decoration_config:
      skip_cloning: true
    labels:
      ci-operator.openshift.io/prowgen-controlled: "true"
      pj-rehearse.openshift.io/can-be-rehearsed: "true"
    name: pull-ci-openshift-windows-machine-config-operator-master-tools-test-e2e
    rerun_command: /test tools-test-e2e
    spec:
      containers:
      - args:
        - --artifact-dir=$(ARTIFACTS)
        - --give-pr-author-access-to-namespace=true
        - --secret-dir=/usr/local/tools-test-e2e-cluster-profile
        - --sentry-dsn-path=/etc/sentry-dsn/ci-operator
        - --target=tools-test-e2e
        - --template=/usr/local/tools-test-e2e
        command:
        - ci-operator
        env:
        - name: CLUSTER_TYPE
          value: aws
        - name: CONFIG_SPEC
          valueFrom:
            configMapKeyRef:
              key: openshift-windows-machine-config-operator-master.yaml
              name: ci-operator-master-configs
        - name: JOB_NAME_SAFE
          value: tools-test-e2e
        - name: TEST_COMMAND
          value: make test-tools-e2e
        image: ci-operator:latest
        imagePullPolicy: Always
        name: ""
        resources:
          requests:
            cpu: 10m
        volumeMounts:
        - mountPath: /usr/local/tools-test-e2e-cluster-profile
          name: cluster-profile
        - mountPath: /usr/local/tools-test-e2e
          name: job-definition
          subPath: cluster-launch-installer-e2e.yaml
        - mountPath: /etc/sentry-dsn
          name: sentry-dsn
          readOnly: true
      serviceAccountName: ci-operator
      volumes:
      - name: cluster-profile
        projected:
          sources:
          - secret:
              name: cluster-secrets-aws
      - configMap:
          name: prow-job-cluster-launch-installer-e2e
        name: job-definition
      - name: sentry-dsn
        secret:
          secretName: sentry-dsn
    trigger: (?m)^/test( | .* )tools-test-e2e,?($|\s.*)
  - agent: kubernetes
    always_run: true
    branches:
    - master
    context: ci/prow/verify
    decorate: true
    decoration_config:
      skip_cloning: true
    labels:
      ci-operator.openshift.io/prowgen-controlled: "true"
      pj-rehearse.openshift.io/can-be-rehearsed: "true"
    name: pull-ci-openshift-windows-machine-config-operator-master-verify
    rerun_command: /test verify
    spec:
      containers:
      - args:
        - --artifact-dir=$(ARTIFACTS)
        - --give-pr-author-access-to-namespace=true
        - --sentry-dsn-path=/etc/sentry-dsn/ci-operator
        - --target=verify
        command:
        - ci-operator
        env:
        - name: CONFIG_SPEC
          valueFrom:
            configMapKeyRef:
              key: openshift-windows-machine-config-operator-master.yaml
              name: ci-operator-master-configs
        image: ci-operator:latest
        imagePullPolicy: Always
        name: ""
        resources:
          requests:
            cpu: 10m
        volumeMounts:
        - mountPath: /etc/sentry-dsn
          name: sentry-dsn
          readOnly: true
      serviceAccountName: ci-operator
      volumes:
      - name: sentry-dsn
        secret:
          secretName: sentry-dsn
    trigger: (?m)^/test( | .* )verify,?($|\s.*)
